### PR TITLE
chore: push release images to dockerhub

### PR DESCRIPTION
**Pull request by drpebcak**

### CODE REVIEW

**Comment by thedadams** [comment]
If I understand correctly, a user could run the Docker Hub image with `docker run acornlabs/otto8-ai/otto8`. Is that right?

**Comment by drpebcak** [comment]
`docker run acornlabs/otto8` - afaik docker hub still doesn't support nesting the image under a second namespace like that.

**Review by thedadams — APPROVED** [review]
This looks good, but hoping we can get the `otto8-ai` org on Docker Hub for hosting this image.

**Comment by drpebcak** [comment]
they dont allow dashes, but i can get `otto8`.

**Comment by drpebcak** [comment]
I changed it to otto8

**Review by thedadams — APPROVED** [review]

**Pull request merged**
